webapp/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_session import Session

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'dexlab'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)
    app.config["SESSION_PERMANENT"] = False
    app.config["SESSION_TYPE"] = "filesystem"
    Session(app)
    
    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix = '/')
    app.register_blueprint(auth, url_prefix = '/')

    return app

webapp/website/auth.py
from distutils.log import error
from unicodedata import name
from urllib.parse import uses_relative
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
import requests
from .models import *


auth = Blueprint('auth', __name__)


@auth.route('/login', methods = ['GET', 'POST'])
def login():
    email = request.form.get('email')
    password = request.form.get('password')

    data = {}
    data['email'] = email
    data['password'] = password
    if request.method == 'POST':
        req = requests.post('http://149.165.155.4:3000/user/login', json = data)
        userData = req.json()
        if req.status_code == 200:
            # User(userData)
            print(session,"=-=-=-=-", userData["name"])
            session["name"] = userData["name"]
            session["user_id"] = userData["user_id"]
            return redirect(url_for('views.getrecipes'))
        elif req.status_code == 401:
            flash('Incorrect credentials!', category="error")
        elif req.status_code == 403:
            flash('Email ID not found! Please create a new account!', category="error")
    return render_template("login.html")

@auth.route('/logout')
def logout():
    flash('Logged Out Successfully', category='success')
    session['name'] = None
    session["user_id"] = None
    return render_template("home.html")

@auth.route('/sign-up', methods = ['GET', 'POST'])
def sign_up():
    email = request.form.get('email')
    firstName = request.form.get('firstName')
    password1 = request.form.get('password1')
    password2 = request.form.get('password2')

    data = {}

    data['email'] = email
    data['password'] = password1
    data['name'] = firstName
    
    if password1 != password2:
        flash('Passwords dont match', category="error")
    elif request.method == 'POST':
        req = requests.post('http://149.165.155.4:3000/user/signup', json = data)
        userData = req.json()

        if req.status_code == 401:
            flash('Email already exists', category="error")
        elif req.status_code == 503:
            flash('Something went wrong!', category="error")
        else:
            session["name"] = userData["name"]
            session["user_id"] = userData["user_id"]
            return redirect(url_for('views.getrecipes'))

    return render_template("signup.html")

webapp/website/views.py
from urllib.request import urlopen
from flask import Blueprint, render_template, jsonify
from flask_login import current_user
from flask_login import login_required, current_user
# from requests import session
import requests
import json
from flask import Blueprint, render_template, request, flash, redirect, url_for, session

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("home.html")

@views.route('/getrecipes', methods = ['GET','POST'])
def getrecipes():
    
    #print(session['name'])
    n_ingredients = request.form.get("n_ingredients")
    cooking_time = request.form.get("cooking_time")
    
    #print(n_ingredients, cooking_time)
    if n_ingredients or cooking_time:
        url = 'http://149.165.155.4:3000/recipes/filter?user_id='+ str(session["user_id"])

        if n_ingredients and not cooking_time:
            url += '&n_steps=' + str(n_ingredients)
        elif cooking_time and not n_ingredients:
            url += '&cooktime=' + str(cooking_time)
        elif n_ingredients and cooking_time:
            url += '&cooktime=' + str(cooking_time) + '&n_steps=' + str(n_ingredients)
        
        req = requests.get(url)
        filter_data = req.json()
        return render_template("getrecipes.html", req_data = filter_data)

    else:

        status_show = request.args.get('status', None)
        recipe_id_show = request.args.get('recipe_id_get', None)

        if len(session) != 0:
            data = {}
            data['user_id'] = session['user_id']
            data['recipe_id'] = recipe_id_show

            if status_show is not None:

                if status_show == 'True':
                    url = 'http://149.165.155.4:3000/activity/deletefavourite'
                    req_status = requests.post(url, json = data)
                else:
                    url = 'http://149.165.155.4:3000/activity/addfavourite'
                    req_status = requests.post(url, json = data)

            url = 'http://149.165.155.4:3000/recipes/getall?user_id='+ str(session["user_id"])
            print(url)
            req = requests.get(url)
            req_data = req.json()
            
            return render_template("getrecipes.html", req_data = req_data)

        else:
            return render_template("getrecipes.html")
        
@views.route('/recipeinfo', methods = ['GET','POST'])
def recipeinfo():
    recipe_id_show = request.args.get('recipe_id_get', None)
    
    if len(session) != 0:
        url = 'http://149.165.155.4:3000/recipes/metadata?recipe_id='+ str(recipe_id_show) + '&user_id=' + str(session["user_id"])
        req = requests.get(url)
        recipe_data = req.json()
        

    
    return render_template("recipeinfo.html", recipe_data = recipe_data)


@views.route('/userfavourites', methods = ['GET','POST'])
def userfavourites():

    if len(session) != 0:
        
        recipe_id_show = request.args.get('recipe_id_get', None)
        status_show = request.args.get('status', None)
        
        data = {}
        data['user_id'] = session['user_id']
        data['recipe_id'] = recipe_id_show

        if status_show:
            url_status = 'http://149.165.155.4:3000/activity/deletefavourite'
            req_status = requests.post(url_status, json = data)

        url = 'http://149.165.155.4:3000/activity/getfavourite'
        req = requests.post(url, json = data)
        # user_data = req.json()

        if req.status_code == 204:
            user_data = []
        else:
            user_data = req.json()
            print(user_data)

        return render_template("userfavourites.html", req_data = user_data)
    else:
        return render_template("userfavourites.html")

webapp/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link 
    href = "{{ url_for('static', filename='main.css') }}" 
    rel="stylesheet" 
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link 
    rel="stylesheet" 
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" 
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
    crossorigin="anonymous"
    />
    <link 
    href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet"
    />
    <link 
    href='https://fonts.googleapis.com/css?family=Merienda' 
    rel='stylesheet'
    />
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar-collapse-main"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-collapse-main">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="home" href="/"><i>Cooking made Easy!! </i></a>
          <a class="nav-item nav-link" id="home" href="/getrecipes">Recipes</a>
          <!-- <a class="nav-item nav-link" id="home" href="/">Quick Recipes</a>
          <a class="nav-item nav-link" id="home" href="/">Top Recipes of the month</a> -->
          {% if session.name %}
          <a class="nav-item nav-link" id="home" href="/userfavourites">{{ session.name }}</a>
          <div class = "d-flex justify-content-end">
            <li class="nav-item"> <a class="nav-item nav-link" id="login" href="/logout">Logout</a></li>
        </div>
          {% else %}    
          <div class = "d-flex justify-content-end">
            <li class="nav-item"> <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a></li>
            <li class="nav-item"> <a class="nav-item nav-link" id="login" href="/login">Login</a></li>
        </div>
        {% endif %}
        </div>
      </div>
    </nav>
    
    {% with messages = get_flashed_messages(with_categories = true) %}
    {% if messages %}
        {% for category, message in messages %}
        {% if category == 'error' %}
        <div class = "alert alert-danger alert-dismissable fade show" role = "alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% else %}
        <div class = "alert alert-success alert-dismissable fade show" role = "alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}
    {% block content %} 
    <div class = "landing_page">
      <div class="container">
        <div class = "home">
          <div class="container-fluid position-relative overflow-hidden mb-4 mb-sm-0" style="min-height: 95vh;">
              <div class="container mt-xl-5 mt-lg-5">
                <div class="row pt-xl-5 pt-lg-5 d-sm-flex flex-column-reverse flex-lg-row text-center text-md-start">
                  <div class="col-xl-6 col-lg-7 pt-xl-5 mt-xl-5 mt-lg-5">
                    <h3 class="h3 fw-semibold opacity-75">
                      <!--       TYPED JS       -->
                      <span id="typed"></span>
                    </h3>
                    <h1 class="h1 fw-bold">Cooking made easy!!</h1>
                    <p class="">Delicious recipes on a single click - Project by Team DexLab</p>
                    <a href="/getrecipes" class="btn btn-dark">Get started</a>
                  </div>
                  <div class="col-xl-6 col-lg-5 mt-lg-5 position-relative">
                    <img src="https://i.pinimg.com/originals/88/5f/62/885f62675329c0f8a605ffe87bd61657.jpg" alt="" class="img-fluid scale-up">
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
    {% endblock %}
    
      <script 
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
      crossorigin="anonymous">
    </script>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='main.js') }}"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  </body>
</html>

webapp/website/templates/getrecipes.html
{% extends "base.html" %} {% block title %} Get Recipes {% endblock %}
{% block content %}
<div class = "landing_page">
{% if session.name %}
<div class="container">
<!-- <h1 class="h1 fw-bold">Hello {{ session.name }} </h1> -->
<h3 align = "left"></h3><br>
<form method = 'POST' style = "max-width:500px" class="form-inline">
    <div class = "form-group">
        <label for="numberIngredients">Number of Cooking steps : &nbsp;</label>
        <input 
        type = "text"
        id = "n_ingredients"
        name = "n_ingredients"
        maxlength="3"
        size = "8"
        />
        &nbsp;&nbsp;
        <!-- <button class="btn btn-dark", onclick="addTextBox()">Add more</button> -->
        <!-- Add More <input type="button" class = "btn btn-dark", onclick="addTextBox()"> -->

        <!-- <button class="btn btn-info sign-bttn">  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square-dotted" viewBox="0 0 16 16">
            <path d="M2.5 0c-.166 0-.33.016-.487.048l.194.98A1.51 1.51 0 0 1 2.5 1h.458V0H2.5zm2.292 0h-.917v1h.917V0zm1.833 0h-.917v1h.917V0zm1.833 0h-.916v1h.916V0zm1.834 0h-.917v1h.917V0zm1.833 0h-.917v1h.917V0zM13.5 0h-.458v1h.458c.1 0 .199.01.293.029l.194-.981A2.51 2.51 0 0 0 13.5 0zm2.079 1.11a2.511 2.511 0 0 0-.69-.689l-.556.831c.164.11.305.251.415.415l.83-.556zM1.11.421a2.511 2.511 0 0 0-.689.69l.831.556c.11-.164.251-.305.415-.415L1.11.422zM16 2.5c0-.166-.016-.33-.048-.487l-.98.194c.018.094.028.192.028.293v.458h1V2.5zM.048 2.013A2.51 2.51 0 0 0 0 2.5v.458h1V2.5c0-.1.01-.199.029-.293l-.981-.194zM0 3.875v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zM0 5.708v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zM0 7.542v.916h1v-.916H0zm15 .916h1v-.916h-1v.916zM0 9.375v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zm-16 .916v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zm-16 .917v.458c0 .166.016.33.048.487l.98-.194A1.51 1.51 0 0 1 1 13.5v-.458H0zm16 .458v-.458h-1v.458c0 .1-.01.199-.029.293l.981.194c.032-.158.048-.32.048-.487zM.421 14.89c.183.272.417.506.69.689l.556-.831a1.51 1.51 0 0 1-.415-.415l-.83.556zm14.469.689c.272-.183.506-.417.689-.69l-.831-.556c-.11.164-.251.305-.415.415l.556.83zm-12.877.373c.158.032.32.048.487.048h.458v-1H2.5c-.1 0-.199-.01-.293-.029l-.194.981zM13.5 16c.166 0 .33-.016.487-.048l-.194-.98A1.51 1.51 0 0 1 13.5 15h-.458v1h.458zm-9.625 0h.917v-1h-.917v1zm1.833 0h.917v-1h-.917v1zm1.834-1v1h.916v-1h-.916zm1.833 1h.917v-1h-.917v1zm1.833 0h.917v-1h-.917v1zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
          </svg>&nbsp; Add more</button>
        <br><br> -->

        <label for="cookingTime">Cooking Time (in mins): &nbsp;</label>
        <input
        type = "text"
        id = "cooking_time"
        name = "cooking_time"
        /><br><br>
        &nbsp;&nbsp;&nbsp;
        <button type="submit" id = "get_recipes_btn" class="btn btn-light">Get Recipes</button>
      </div>
    </form>
</div>
<form method="POST">
    <br>
<div class="container">
    <h3>Delicious Recipes : </h3>
        <table class="table table-striped">
            <thead>
              <tr>
                <!-- <th scope="col">Recipe ID</th> -->
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Average Rating</th>
                <th scope="col">Cooking Time</th>
                <th scope="col">Image</th>
                <th scope="col">Steps Count</th>
                <th scope="col">Add to Favorites</th>
              </tr>
            </thead>
            <tbody>
                {% for i in req_data %}
              <tr>
                <!-- <td><a href="{{ url_for('views.recipeinfo', recipe_id_get = i['recipe_id']) }}" >{{ i['recipe_id'] }}</a></td> -->
                <td><a href="{{ url_for('views.recipeinfo', recipe_id_get = i['recipe_id']) }}" >{{ i['name'] }}</a></td>
                <td>{{ i['description'] }}</td>
                <td>{{ i['avg_rating'] }}</td>
                <td>{{ i['time'] }}</td>
                <td class = "recipe_images">
                    <img src = "{{ i['image'] }}">
                </td>
                <td>{{ i['steps_cnt'] }}</td>
                {% if i['fav'] %}
                <td><a href="{{ url_for('views.getrecipes', status = i['fav'], recipe_id_get = i['recipe_id']) }}"><span class="material-icons md-light">favorite</span></a></td>
                {% else %}
                <td><a href="{{ url_for('views.getrecipes', status = i['fav'], recipe_id_get = i['recipe_id']) }}"><span class="material-icons md-light">favorite_border</span></a></td>
                {% endif %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
  </form>
    {% else %}
    <section class="vh-100 bg-image">
      <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-9 col-lg-7 col-xl-6">
              <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                  <h2 class="text-uppercase text-center mb-5">Please Login/Sign-Up to continue.</h2>
                  <div class="d-flex justify-content-center">
                    <a href = "/login"
                      class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Login</a>
                    </div><br>
                    <div class="d-flex justify-content-center">
                    <!-- <a href = "/login" class = "btn btn-primary">Login</a> -->
                    <a href = "/sign-up" 
                    class = "btn btn-success btn-block btn-lg gradient-custom-4 text-body">Sign-Up</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- <div class = "init-getrecipes">
        <h1 class="h1 fw-bold">You haven't registered with us. Please Login/Sign-Up to continue.</h1>
        <a href = "/login" class = "btn btn-primary">Login</a>
        <a href = "/sign-up" class = "btn btn-primary">Sign-Up</a>
    </div> -->
    {% endif %}

  </div>
{% endblock %}

webapp/website/templates/home.html
{% extends "base.html" %} {% block title %} Home {% endblock %}

webapp/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block
    content %}
    <div class="landing_page">
    <section class="vh-100 bg-image">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-9 col-lg-7 col-xl-6">
            <div class="card" style="border-radius: 15px;">
              <div class="card-body p-5">
                <h2 class="text-uppercase text-center mb-5">LOGIN</h2>
  
                <form method = "POST">
  
                  <div class="form-outline mb-4">
                    <input type="email" 
                    id="form3Example3cg" 
                    class="form-control form-control-lg" 
                    name = "email"
                    />
                    <label class="form-label" for="form3Example3cg">Your Email</label>
                  </div>
  
                  <div class="form-outline mb-4">
                    <input type="password" 
                    id="form3Example4cg" 
                    class="form-control form-control-lg" 
                    name = "password"
                    />
                    <label class="form-label" for="form3Example4cg">Password</label>
                  </div>
  
                  
                  <div class="d-flex justify-content-center">
                    <button type="submit"
                      class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Login</button>
                  </div>
  
                </form>
  
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
    <!-- <div class = "landing_page">
    <form method="POST">
        <h3 align="center">Login</h3>
        <div class="form-group">
          <label for="email">Email Address</label>
          <input
            type="email"
            class="form-control"
            id="email"
            name="email"
            placeholder="Enter email"
          />
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input
            type="password"
            class="form-control"
            id="password"
            name="password"
            placeholder="Enter password"
          />
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Login</button>
      </form>
      </div> -->
    {% endblock %}

webapp/website/templates/recipeinfo.html
{% extends "base.html" %} {% block title %} Get Recipes {% endblock %}
{% block content %}
<div class = "landing_page">

{% if session.name %}

<!-- <h1 class="h1 fw-bold">Hello {{ session.name }} </h1> -->

<div class = "recipe_info_box">
    <h2 class="h2 fw-bold"><span style="text-transform:uppercase">{{ recipe_data['name'] }}</span></h2>
    <p class = "recipe_images_info"><img src = "{{ recipe_data['image'] }}"></p>
    <div class="container">
        <div class = "home">
          <div class="container-fluid position-relative overflow-hidden mb-4 mb-sm-0" style="min-height: 95vh;">
              <div class="container mt-xl-1 mt-lg-5">
                <div class="row pt-xl-5 pt-lg-5 d-sm-flex flex-column-reverse flex-lg-row text-center text-md-start">
                  <div class="col-xl-6 col-lg-7 pt-xl-5 mt-xl-5 mt-lg-5">
                    <h3 class="h3 fw-semibold opacity-75">
                      <!--       TYPED JS       -->
                      <span id="typed"></span>
                    </h3>
                    <h3>Description: </h3><p style="font-size: 18px">{{ recipe_data['description'] }} </p><br>
                    <h3>Cooking Time:</h3><p style="font-size: 18px">{{ recipe_data['time'] }} </p><br>
                    <h3>Steps count: </h3><p style="font-size: 18px">{{ recipe_data['steps_cnt'] }} </p><br>
                    <h3>Average Rating: </h3><p style="font-size: 18px">{{ recipe_data['avg_rating'] }} </p><br>
                  </div>
                  <div class="col-xl-6 col-lg-5 mt-lg-5 position-relative">
                    <h2>Steps: </h2><br>
                    <ol>
                        {% for step in  recipe_data['steps'] %}
                        
                        <li style="font-size: 20px">{{ step }}</li>
                        
                        {% endfor %}
                    </ol>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>
</div>

{% endif %}

</div>
{% endblock %}

webapp/website/templates/userfavourites.html
{% extends "base.html" %} {% block title %} Get Recipes {% endblock %}
{% block content %}
<div class = "landing_page">
    {% if session.name %}

    <div class="container">
            <table class="table table-striped">
                <thead>
                  <tr>
                    <!-- <th scope="col">Recipe ID</th> -->
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Average Rating</th>
                    <th scope="col">Cooking Time</th>
                    <th scope="col">Image</th>
                    <th scope="col">Steps Count</th>
                    <th scope="col">Remove from Favorites</th>
                  </tr>
                </thead>
                <tbody>
                    {% if req_data|length == 0 %}
                    <div class="container">
                        <div class = "home">
                          <div class="container-fluid position-relative overflow-hidden mb-4 mb-sm-0" style="min-height: 95vh;">
                              <div class="container mt-xl-5 mt-lg-5">
                                <div class="row pt-xl-5 pt-lg-5 d-sm-flex flex-column-reverse flex-lg-row text-center text-md-start">
                                  <div class="col-xl-6 col-lg-7 pt-xl-5 mt-xl-5 mt-lg-5">
                                    <h3 class="h3 fw-semibold opacity-75">
                                      <!--       TYPED JS       -->
                                      <span id="typed"></span>
                                    </h3>
                                    <h1 class="h1 fw-bold">Nothing to show here!</h1>
                                    <p class="">Please add recipes in your favourite list!</p>
                                    <a href="/getrecipes" class="btn btn-dark">Browse Recipes</a>
                                  </div>
                                  <div class="col-xl-6 col-lg-5 mt-lg-5 position-relative">
                                    <a href = "/getrecipes"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Heart_or_Favorites_Flat_Icon_Vector.svg/1024px-Heart_or_Favorites_Flat_Icon_Vector.svg.png" alt="" class="img-fluid scale-up"></a>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                      </div>
                    {% else %}
                    <h3 class="h3 fw-bold">Your favourite recipes!!</h1>
                    {% for i in req_data %}
                  <tr>
                      
                    <!-- <td><a href="{{ url_for('views.recipeinfo', recipe_id_get = i['recipe_id']) }}" >{{ i['recipe_id'] }}</a></td> -->
                    <td><a href="{{ url_for('views.recipeinfo', recipe_id_get = i['recipe_id']) }}" >{{ i['name'] }}</a></td>
                    <td>{{ i['description'] }}</td>
                    <td>{{ i['avg_rating'] }}</td>
                    <td>{{ i['time'] }}</td>
                    <td class = "recipe_images">
                        <img src = "{{ i['image'] }}">
                    </td>
                    <td>{{ i['steps_cnt'] }}</td>
                    <td><a href="{{ url_for('views.userfavourites', status = True, recipe_id_get = i['recipe_id']) }}"><span class="material-icons md-light">clear</span></a></td>
                  </tr>
                  {% endfor %}
                  {% endif %}
                </tbody>
              </table>
        </div>

    {% endif %}
</div>
{% endblock %}